### 강의 목록 조회
GET http://localhost:8085/lectures
Accept: text/html

### 강의 등록
POST http://localhost:8085/lectures
Content-Type: application/json
Accept: application/json

{
  "name": "김영한 JPA",
  "price": 15000
}

### 강의 등록2
POST http://localhost:8085/lectures
Content-Type: application/json
Accept: application/json

{
"name": "김영한 JPA2",
"price": 10000
}

